Diary.UI/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Diary.UI.DataContext;
using Diary.UI.Models;

namespace Diary.UI.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }



        // GET: Customers/Edit/5
        public async Task<IActionResult> AddorEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.Where(x => x.Lawsuit.Id == id).FirstOrDefaultAsync();
            if (customer == null)
            {
                return NotFound();
            }
            return PartialView("AddorEdit", customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddorEdit(int id, [Bind("ClientType,ClientName,Address,Phone,SendSMS,Id")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
       
        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }
    }
}

Diary.UI/Controllers/DocumentsController.cs
using Diary.UI.DataContext;
using Diary.UI.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Diary.UI.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DocumentsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index( int ?  Id)
        {

            if (Id == null)
            {
                Id = 1;
            }
            var documents = await _context.Documents.Where(f => f.LawsuitId == Id).ToListAsync();
            return View(documents);
        }
        public IActionResult UploadFile()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UploadFile(IFormFile FormFile)
        {
            byte[] Content;


            string filename = Path.GetFileName(FormFile.FileName);
            string contentType = FormFile.ContentType;

            using (var memoryStream = new MemoryStream())
            {
                await FormFile.CopyToAsync(memoryStream);

                if (memoryStream.Length < 2097152)
                {

                    Content = memoryStream.ToArray();
                    Document document = new Document()
                    {
                        LawsuitId = 1,
                        Data = Content,
                        FileName = filename,
                        ContentType = contentType
                    };

                    _context.Documents.Add(document);
                    _context.SaveChanges();

                }
                else
                {
                    ModelState.AddModelError("File", "The file is too large.");
                }
            }

            return RedirectToAction("Index", "Home");

        }
        public async Task<FileResult> DownloadFileFromFileSystem(int id)
        {
            var file = await _context.Documents.FindAsync(id);

            if (file == null) return null;
            return File(file.Data, file.ContentType, file.FileName);
        }
        byte[] ReadFile(string sPath)
        {
            
            byte[] data = null;            
            FileInfo fInfo = new FileInfo(sPath);
            long numBytes = fInfo.Length;            
            FileStream fStream = new FileStream(sPath, FileMode.Open, FileAccess.Read);
            BinaryReader br = new BinaryReader(fStream);        
            data = br.ReadBytes((int)numBytes);
            return data;
        }

    }
}

Diary.UI/Controllers/LawsuitsController.cs
using Diary.UI.DataContext;
using Diary.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;


namespace Diary.UI.Controllers
{
    [Authorize(AuthenticationSchemes = "Cookies")]
    public class LawsuitsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LawsuitsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Lawsuits
        public IActionResult Index()
        {
            var item = _context.Lawsuits.Select(x => new LawsuitViewModel()
            {
                Id = x.Id,
                Customer = x.Customers.Select(x => x.ClientName).FirstOrDefault(),
                CaseCategory = x.CaseCategory.Category,
                Court = x.Courts.CourtName,
                Description = x.Description,
                Casetype = x.Casetype.ToString(),
                CreateOn = x.CreateOn,
                Status = x.Status.ToString()

            }).AsEnumerable();


            var TodayCases = item.Where(x => x.CreateOn.Equals(DateTime.Now));
            var nextdayacases= item;
            return View(nextdayacases.ToList());
        }

      
        // GET: Lawsuits/Create
        public IActionResult Create()
        {
            var model = new LawsuitInputModel()
            {
                CategoryList= (List<SelectListItem>)_context.CaseCategories.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Category }).ToList(),
                ApplicationUserList = (List<SelectListItem>)_context.ApplicationUsers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Name }).ToList(),
                CourtList = (List<SelectListItem>)_context.Court.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CourtName }).ToList(),
                CustomersList = (List<SelectListItem>)_context.Customers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.ClientName }).ToList()
            };
            return View(model);
        }

        // POST: Lawsuits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LawsuitInputModel item)
        {
            if (ModelState.IsValid)
            {

                var lawsuit = new Lawsuit()
                {
                    Courts = _context.Court.Find(item.CourtsId),
                    FileNo=item.FileNo,
                    CaseCategory= _context.CaseCategories.Find(item.CategoryId),
                    Description = item.Description,
                    Casetype = item.Casetype,
                    Status = item.Status,
                    ApplicationUser = _context.ApplicationUsers.Find(item.ApplicationUserId),
                    CreateOn=DateTime.Today
                };


                _context.Add(lawsuit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Lawsuits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            

            var lawsuit = await _context.Lawsuits.Where(x => x.Id == id).Select(x => new LawsuitEditModel()
            {
                Id = x.Id,FileNo=x.FileNo,                
                CourtsId = x.Courts.Id,
                Description = x.Description,
                Casetype = x.Casetype,
                Status = x.Status,
                ApplicationUserId=x.ApplicationUser.Id,
                HearingsList = (ICollection<HearingViewModel>)x.Hearings.Where(x => x.Lawsuits.Id == id).Select(e => new HearingViewModel()
                {
                    Id = e.Id,
                    Description = e.Description,
                    CreateOn = e.CreateOn
                }).ToList(),
                DoucmentList = (ICollection<DocumentViewModel>)x.Documents.Where(x => x.LawsuitId == id).Select(e => new DocumentViewModel()
                {
                 FileName=e.FileName,ContentType=e.ContentType,Id=e.Id
                }).ToList(),

                ApplicationUserList = (List<SelectListItem>)_context.ApplicationUsers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Name }).ToList(),
                CourtList = (List<SelectListItem>)_context.Court.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CourtName }).ToList(),
                CustomersList = x.Customers.Where(x => x.Lawsuit.Id==id).ToList()

            }).FirstOrDefaultAsync();
                
            if (lawsuit == null)
            {
                return NotFound();
            }
            return View(lawsuit);
        }

        // POST: Lawsuits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FileNo,Description,CourtsId,CustomersId,ApplicationUserId,Status,Casetype,CreateOn")] LawsuitEditModel item)
        {
            var lawsuit=(dynamic)null;
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                     lawsuit = new Lawsuit()
                    {
                        Id=item.Id,
                        Courts = _context.Court.Find(item.CourtsId),
                        FileNo = item.FileNo,
                       
                        Description = item.Description,
                        Casetype = item.Casetype,
                        Status = item.Status,
                        ApplicationUser = _context.ApplicationUsers.Find(item.ApplicationUserId),
                        CreateOn = DateTime.Today
                    };
                    _context.Update(lawsuit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LawsuitExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
               
                return RedirectToAction(nameof(Index));
            }
             lawsuit = await _context.Lawsuits.Where(x => x.Id == id).Select(x => new LawsuitEditModel()
            {
                Id = x.Id,
                FileNo = x.FileNo,
                
                CourtsId = x.Courts.Id,
                Description = x.Description,
                Casetype = x.Casetype,
                Status = x.Status,
                ApplicationUserId = x.ApplicationUser.Id,
                HearingsList = (ICollection<HearingViewModel>)x.Hearings.Where(x => x.Lawsuits.Id == id).Select(e => new HearingViewModel()
                {
                    Id = e.Id,
                    Description = e.Description,
                    CreateOn = e.CreateOn
                }).ToList(),
                ApplicationUserList = (List<SelectListItem>)_context.ApplicationUsers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Name }).ToList(),
                CourtList = (List<SelectListItem>)_context.Court.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CourtName }).ToList(),
                //CustomersList = (List<SelectListItem>)_context.Customers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CustomerName }).ToList()


            }).FirstOrDefaultAsync();
            return View(lawsuit);
        }

        // GET: Lawsuits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lawsuit = await _context.Lawsuits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lawsuit == null)
            {
                return NotFound();
            }

            return View(lawsuit);
        }

        // POST: Lawsuits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lawsuit = await _context.Lawsuits.FindAsync(id);
            _context.Lawsuits.Remove(lawsuit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LawsuitExists(int id)
        {
            return _context.Lawsuits.Any(e => e.Id == id);
        }


        [HttpGet]
        public IActionResult AddHearing(int? Id)
        {
    
         
                var item = new HearingViewModel()
                {
                    Lawsuits=_context.Lawsuits.Find(Id),Description=""
                };
            return View(item);
          
           
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public IActionResult AddHearing(int Id,  HearingViewModel item)
        {
            if(Id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var hearing = new Hearing()
                {
                    Description = item.Description,
                    Lawsuits = _context.Lawsuits.Find(item.Lawsuits.Id),

Diary.UI/Views/Lawsuits/Edit.cshtml
@model Diary.UI.Models.LawsuitEditModel

@{
    ViewData["Title"] = "Edit";
}


    <!-- Tabs navs -->
<ul class="nav nav-tabs mb-3" id="ex-with-icons" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" id="ex-with-icons-tab-1" data-toggle="tab" href="#ex-with-icons-tabs-1" role="tab"
           aria-controls="ex-with-icons-tabs-1" aria-selected="true"><i class="fas fa-chart-pie fa-fw me-2">Sales</i>                    </a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="ex-with-icons-tab-2" data-toggle="tab" href="#ex-with-icons-tabs-2" role="tab"
           aria-controls="ex-with-icons-tabs-2" aria-selected="false"><i class="fas fa-chart-line fa-fw me-2"></i>Hearing Info</a>
    </li>

    <li class="nav-item" role="presentation">
        <a class="nav-link" id="ex-with-icons-tab-3" data-toggle="tab" href="#ex-with-icons-tabs-3" role="tab" 
           aria-controls="ex-with-icons-tabs-2" aria-selected="false"><i class="fas fa-chart-line fa-fw me-2"></i>Documents</a>
    </li>

</ul>
    <!-- Tabs navs -->
<div class="tab-content" id="ex-with-icons-content">
    <div class="tab-pane fade show active" id="ex-with-icons-tabs-1" role="tabpanel" aria-labelledby="ex-with-icons-tab-1">
        <div class="row">
            <div class="col-xl-6 col-md-5">
                <div class="card">
                    <div class="card-body">
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group row">
                                <label asp-for="Id" class="col-sm-3 col-form-label text-sm-left"></label>
                                <div class="col-sm-9">
                                    <input asp-for="Id" class="form-control" />
                                    <span asp-validation-for="Id" class="text-danger"></span>
                                </div>

                            </div>
                            <div class="form-group row">
                                <label asp-for="FileNo" class="col-sm-3 col-form-label text-sm-left"></label>
                                <div class="col-sm-9">
                                    <input asp-for="FileNo" class="form-control" />
                                    <span asp-validation-for="FileNo" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Description" class="col-sm-3 col-form-label text-sm-left"></label>
                                <div class="col-sm-9">
                                    <textarea asp-for="Description" rows="4" class="form-control"> </textarea>
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                @*<label asp-for="CustomersId" class="col-sm-3 col-form-label text-sm-left"></label>
                                    <div class="col-sm-9">

                                        <select asp-for="CustomersId" class="form-control custom-select" asp-items="Model.CustomersList"><option>Please select one</option></select>
                                        <span asp-validation-for="CustomersId" class="text-danger"></span>
                                    </div>*@
                            </div>
                            <div class="form-group row">
                                <label asp-for="CourtsId" class="col-sm-3 col-form-label text-sm-left"></label>
                                <div class="col-sm-9">
                                    <select asp-for="CourtsId" class="form-control custom-select" asp-items="Model.CourtList"><option>Please select one</option></select>

                                    <span asp-validation-for="CourtsId" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label asp-for="ApplicationUserId" class="col-sm-3 col-form-label text-sm-left"></label>
                                <div class="col-sm-9">
                                    <select asp-for="ApplicationUserId" class="form-control custom-select" asp-items="Model.ApplicationUserList"><option>Please select one</option></select>

                                    <span asp-validation-for="ApplicationUserId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Status" class="col-sm-3 col-form-label text-sm-left"></label>
                                <div class="col-sm-9">
                                    <select asp-for="Status" class="form-control custom-select" asp-items="Html.GetEnumSelectList<Status>()"><option>Please status</option></select>

                                    <span asp-validation-for="Status" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Casetype" class="col-sm-3 col-form-label text-sm-left"></label>
                                <div class="col-sm-9">
                                    <select asp-for="Casetype" class="form-control custom-select" asp-items="Html.GetEnumSelectList<Casetype>()"><option>Please status</option></select>

                                    <span asp-validation-for="Casetype" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row justify-content-end">
                                <div class="col-sm-9">
                                    <div>
                                        @if (Model.Id != 0)
                                        {
                                            <button type="submit" class="btn btn-primary ">Update</button>
                                        }
                                        else
                                        {
                                            <button type="submit" class="btn btn-primary ">Submit</button>
                                        }

                                        <a class="btn btn-dark " asp-controller="lawsuits" asp-action="Index">Cancel</a>
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            <div class="col-xl-6 col-md-5">
                <div class="card">
                    <a onclick="showInPopup('@Url.Action("AddorEdit","Customers",new { id=Model.Id},Context.Request.Scheme)','New Client')" class="btn btn-success text-white"><i class="fas fa-random"></i> New Client</a>
                    <div class="card-body">
                        <div class="table-responsive no-padding">
                            <table class="table table-hover">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Client type</th>
                                        <th>Client Name</th>
                                        <th>Address</th>
                                        <th>Phone</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.CustomersList)
                                    {
                                        <tr>
                                            <td>@item.ClientType</td>
                                            <td>@item.ClientName</td>
                                            <td>@item.Address</td>
                                            <td><span class="badge badge-success">@item.Phone</span></td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="tab-pane fade" id="ex-with-icons-tabs-2" role="tabpanel" aria-labelledby="ex-with-icons-tab-2">
        <div class="row">
            <div class="col-sm-12">

                <a onclick="showInPopup('@Url.Action("AddHearing","Lawsuits",new { id=Model.Id},Context.Request.Scheme)','New Transaction')" class="btn btn-success text-white"><i class="fas fa-random"></i> New Transaction</a>
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class=" table table-centered table-nowrap mb-0">
                                <thead class="thead-success">
                                    <tr>
                                        <th>
                                            <a onclick="showInPopup('@Url.Action("AddHearing","Lawsuits",new { id=Model.Id},Context.Request.Scheme)','Add Comments')" class="btn btn-success text-white"><i class="fas fa-random"></i> Add Comments</a>
                                        </th>
                                        <th>Particulars</th>



                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.HearingsList)
                                    {

                                        <tr>
                                            <th>  @item.CreateOn.ToString("dd-MMM-yy")</th>
                                            <th>  @item.Description</th>
                                        </tr>



                                    }
                                </tbody>


                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="tab-pane fade" id="ex-with-icons-tabs-3" role="tabpanel" aria-labelledby="ex-with-icons-tab-3">

        @await Html.PartialAsync("_Documents", @Model.DoucmentList)

    </div>
</div>

    @section Scripts{
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Diary.UI/Views/Lawsuits/Index.cshtml
@model IEnumerable<Diary.UI.Models.LawsuitViewModel>

@{
    ViewData["Title"] = "Index";
}

@{ int rowNo = 0; }
<th><a class="btn btn-danger text-white btnEdit clsShow" asp-action="Create">Add</a></th>

<table id="example" class="table">
    <thead class="thead-primary">
        <tr>
            <th>#</th>
            <th>Customer</th>
            <th>Court</th>
            <th>Createdon</th>
            <th><a class="btn btn-danger text-white btnEdit clsShow" asp-action="Create"><i class="bi bi-plus-circle-fill"></i></a></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() >= 0)
        {

            @foreach (var item in Model)
            {
                <tr >
                    <th> @(rowNo += 1)</th>
                    <th>
                        @item.Customer
                    </th>
                    <th>
                        @item.Court
                    </th>
                    <th>
                        @item.CreateOn.ToString("dd/MM/yyyy")
                    </th>
                    <th>
                        <a class="btn btn-info" asp-controller="Lawsuits" asp-action="Edit" asp-route-id="@item.Id">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                            </svg>
                        </a>

                    </th>
                </tr>
            }

        }
    </tbody>
</table>


@section Scripts{

    <link href="~/css/datatables.css" rel="stylesheet" />


    <script>

        $(document).ready(function () {


            $('#example').DataTable();

        });

    </script>
}

Diary.UI/Views/Lawsuits/_Documents.cshtml
@model IEnumerable<Diary.UI.Models.DocumentViewModel>
    <div class="card">
        <div class="row">

            <div class="col-sm-4 border-0">
                <form enctype="multipart/form-data" method="post" asp-controller="Lawsuits" asp-action="UploadFile">
                    <dl>
                        <dt>
                            <label>Upload</label>
                        </dt>
                        <dd>
                            <input type="file" name="FormFile" id="FormFile">

                        </dd>
                    </dl>
                    <input class="btn btn-info" type="submit" value="Upload" />
                </form>
            </div>
            <div class="col-sm-8">



                <div class="card-body">
                    <div class="table-responsive">
                        <table class=" table table-centered table-nowrap mb-0">
                            <thead class="thead-success">
                                <tr>
                                    <th>
                                        File Name
                                    </th>
                                    <th>Content Type</th>
                                    <th></th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @item.FileName
                                    </td>
                                    <td>
                                        @item.ContentType
                                    </td>
                                    <td>
                                        <a asp-controller="Documents" class="class=" btn btn-primary"" asp-action="DownloadFileFromFileSystem" asp-route-id="@item.Id">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                                                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
                                                <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
                                            </svg> Download
                                        </a>

                                    </td>
                                </tr>
                                }
                            </tbody>


                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>