Diary.UI/Models/CourtDTO.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace Diary.UI.Models
{
    public class CourtDTO
    {
        public string CourtName { get; set; }
        public string State { get; set; }
        public string Location { get; set; }
        public string City{ get; set; }
        
    }
    public class CourtInputModel
    {
        public int Id { get; set; }
        public string CourtName { get; set; }
        public int StateId { get; set; }
        public string Location { get; set; }
        public int CityId { get; set; }
        public string CourtTypeId { get; set; }
        public virtual List<SelectListItem> CourtType { get; set; }
        public virtual List<SelectListItem> StateList { get; set; }
        public virtual List<SelectListItem> CityList { get; set; }
    }

}

Diary.UI/Models/CustomerDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Diary.UI.Models
{
    public class CustomerDTO
    {
    }
}

Diary.UI/Models/ErrorViewModel.cs
using System;

namespace Diary.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Diary.UI/Models/LoginDTO.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Diary.UI.Models
{
    public class LoginModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Diary.UI/Controllers/CourtsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Diary.UI.DataContext;
using Diary.UI.Models;
using Diary.UI.Rep;
using Microsoft.AspNetCore.Authorization;

namespace Diary.UI.Controllers
{
    [Authorize(AuthenticationSchemes = "Cookies")]
    public class CourtsController : Controller
    {
        private readonly ApplicationDbContext _context;
       
        public CourtsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Courts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Court.ToListAsync());
        }

     

        // GET: Courts/Create
        public IActionResult Create()
        {
            CourtRep rep = new CourtRep(_context);

            var model = rep.GetCourtInputModel(0);
           
            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CourtInputModel item)
        {
            CourtRep rep = new CourtRep(_context);
            if (ModelState.IsValid)
            {
                var i = await rep.Create(item);
                return RedirectToAction(nameof(Index));
            }
            var model = new CourtInputModel()
            {
                CityId=item.CityId,StateId=item.StateId,CourtTypeId=item.CourtTypeId,
                StateList = (List<SelectListItem>)_context.States.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.StateName }).ToList(),
                CityList = (List<SelectListItem>)_context.Cities.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Name }).ToList(),
                CourtType = (List<SelectListItem>)_context.StringMap.Where(x => x.FiledName.Equals("CourtType")).Select(e => new SelectListItem { Value = e.DisplayCode.ToString(), Text = e.DisplayName }).ToList()
            };
            return View(model);
        }

        // GET: Courts/Edit/5
        public async Task<IActionResult> Edit(int? Id)
        {
            
            CourtRep rep = new CourtRep(_context);
            var court = await rep.GetCourtInputModel(Id);
            if (court == null)
            {
                return NotFound();
            }
            return View(court);
        }

        // POST: Courts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CourtInputModel court)
        {
            CourtRep rep = new CourtRep(_context);
            if (id != court.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                
                var message = await rep.Edit(id, court);                
                return RedirectToAction(nameof(Index));
            }
            return View(court);
        }

    }
}

Diary.UI/Controllers/LawsuitsController.cs
using Diary.UI.DataContext;
using Diary.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;


namespace Diary.UI.Controllers
{
    [Authorize(AuthenticationSchemes = "Cookies")]
    public class LawsuitsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LawsuitsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Lawsuits
        public IActionResult Index()
        {
            var item = _context.Lawsuits.Select(x => new LawsuitViewModel()
            {
                Id = x.Id,
                Customer = x.Customers.Select(x => x.ClientName).FirstOrDefault(),
                CaseCategory = x.CaseCategory.Category,
                Court = x.Courts.CourtName,
                Description = x.Description,
                Casetype = x.Casetype.ToString(),
                CreateOn = x.CreateOn,
                Status = x.Status.ToString()

            }).AsEnumerable();


            var TodayCases = item.Where(x => x.CreateOn.Equals(DateTime.Now));
            var nextdayacases= item;
            return View(nextdayacases.ToList());
        }

      
        // GET: Lawsuits/Create
        public IActionResult Create()
        {
            var model = new LawsuitInputModel()
            {
                CategoryList= (List<SelectListItem>)_context.CaseCategories.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Category }).ToList(),
                ApplicationUserList = (List<SelectListItem>)_context.ApplicationUsers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Name }).ToList(),
                CourtList = (List<SelectListItem>)_context.Court.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CourtName }).ToList(),
                CustomersList = (List<SelectListItem>)_context.Customers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.ClientName }).ToList()
            };
            return View(model);
        }

        // POST: Lawsuits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LawsuitInputModel item)
        {
            if (ModelState.IsValid)
            {

                var lawsuit = new Lawsuit()
                {
                    Courts = _context.Court.Find(item.CourtsId),
                    FileNo=item.FileNo,
                    CaseCategory= _context.CaseCategories.Find(item.CategoryId),
                    Description = item.Description,
                    Casetype = item.Casetype,
                    Status = item.Status,
                    ApplicationUser = _context.ApplicationUsers.Find(item.ApplicationUserId),
                    CreateOn=DateTime.Today
                };


                _context.Add(lawsuit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Lawsuits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            

            var lawsuit = await _context.Lawsuits.Where(x => x.Id == id).Select(x => new LawsuitEditModel()
            {
                Id = x.Id,FileNo=x.FileNo,                
                CourtsId = x.Courts.Id,
                Description = x.Description,
                Casetype = x.Casetype,
                Status = x.Status,
                ApplicationUserId=x.ApplicationUser.Id,
                HearingsList = (ICollection<HearingViewModel>)x.Hearings.Where(x => x.Lawsuits.Id == id).Select(e => new HearingViewModel()
                {
                    Id = e.Id,
                    Description = e.Description,
                    CreateOn = e.CreateOn
                }).ToList(),
                DoucmentList = (ICollection<DocumentViewModel>)x.Documents.Where(x => x.LawsuitId == id).Select(e => new DocumentViewModel()
                {
                 FileName=e.FileName,ContentType=e.ContentType,Id=e.Id
                }).ToList(),

                ApplicationUserList = (List<SelectListItem>)_context.ApplicationUsers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Name }).ToList(),
                CourtList = (List<SelectListItem>)_context.Court.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CourtName }).ToList(),
                CustomersList = x.Customers.Where(x => x.Lawsuit.Id==id).ToList()

            }).FirstOrDefaultAsync();
                
            if (lawsuit == null)
            {
                return NotFound();
            }
            return View(lawsuit);
        }

        // POST: Lawsuits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FileNo,Description,CourtsId,CustomersId,ApplicationUserId,Status,Casetype,CreateOn")] LawsuitEditModel item)
        {
            var lawsuit=(dynamic)null;
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                     lawsuit = new Lawsuit()
                    {
                        Id=item.Id,
                        Courts = _context.Court.Find(item.CourtsId),
                        FileNo = item.FileNo,
                       
                        Description = item.Description,
                        Casetype = item.Casetype,
                        Status = item.Status,
                        ApplicationUser = _context.ApplicationUsers.Find(item.ApplicationUserId),
                        CreateOn = DateTime.Today
                    };
                    _context.Update(lawsuit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LawsuitExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
               
                return RedirectToAction(nameof(Index));
            }
             lawsuit = await _context.Lawsuits.Where(x => x.Id == id).Select(x => new LawsuitEditModel()
            {
                Id = x.Id,
                FileNo = x.FileNo,
                
                CourtsId = x.Courts.Id,
                Description = x.Description,
                Casetype = x.Casetype,
                Status = x.Status,
                ApplicationUserId = x.ApplicationUser.Id,
                HearingsList = (ICollection<HearingViewModel>)x.Hearings.Where(x => x.Lawsuits.Id == id).Select(e => new HearingViewModel()
                {
                    Id = e.Id,
                    Description = e.Description,
                    CreateOn = e.CreateOn
                }).ToList(),
                ApplicationUserList = (List<SelectListItem>)_context.ApplicationUsers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Name }).ToList(),
                CourtList = (List<SelectListItem>)_context.Court.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CourtName }).ToList(),
                //CustomersList = (List<SelectListItem>)_context.Customers.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.CustomerName }).ToList()


            }).FirstOrDefaultAsync();
            return View(lawsuit);
        }

        // GET: Lawsuits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lawsuit = await _context.Lawsuits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lawsuit == null)
            {
                return NotFound();
            }

            return View(lawsuit);
        }

        // POST: Lawsuits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lawsuit = await _context.Lawsuits.FindAsync(id);
            _context.Lawsuits.Remove(lawsuit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LawsuitExists(int id)
        {
            return _context.Lawsuits.Any(e => e.Id == id);
        }


        [HttpGet]
        public IActionResult AddHearing(int? Id)
        {
    
         
                var item = new HearingViewModel()
                {
                    Lawsuits=_context.Lawsuits.Find(Id),Description=""
                };
            return View(item);
          
           
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public IActionResult AddHearing(int Id,  HearingViewModel item)
        {
            if(Id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var hearing = new Hearing()
                {
                    Description = item.Description,
                    Lawsuits = _context.Lawsuits.Find(item.Lawsuits.Id),

Diary.UI/Controllers/SMSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Diary.UI.DataContext;
using Diary.UI.Models;

namespace Diary.UI.Controllers
{
    public class SMSController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SMSController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SMS
        public  IActionResult Index()
        {
            var item =  _context.Recipient.Select(SMSViewModel.ViewModel);
            return View(item.ToList());
        }

        // GET: SMS/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var messagerecipient = await _context.Recipient
                .FirstOrDefaultAsync(m => m.Id == id);
            if (messagerecipient == null)
            {
                return NotFound();
            }

            return View(messagerecipient);
        }

        // GET: SMS/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SMS/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Lawsuit,PhoneNo,Message,IsSend,IsRead")] Messagerecipient messagerecipient)
        {
            if (ModelState.IsValid)
            {
                _context.Add(messagerecipient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(messagerecipient);
        }

       
        
    }
}

Diary.UI/Views/Shared/_Documents.cshtml
@model IEnumerable<Diary.UI.Models.Document>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.LawsuitId)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.LawsuitId)
                </td>

                <td>
                    <a asp-action="DownloadFileFromFileSystem" asp-route-id="@item.Id">Edit</a> |

                </td>
            </tr>
        }
    </tbody>
</table>

Diary.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diary.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/perfect-scrollbar.css" />
    <link rel="stylesheet" href="~/css/prism.css" />
    <link href="~/lib/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">

</head>
<body>

    <div class="wrapper">
        <div class="Preloader-wrapper" style="display: none;"><div class="spinner"> <div class="bounce1"></div> <div class="bounce2"></div> <div class="bounce3"></div> </div> </div>
        <nav class="sidebar">
            <div class="sidebar-content ">
                <a class="sidebar-brand" href="dashboard.html">
                    <img src="">
                </a>
                <ul class="sidebar-nav ps-container ps-theme-default ps-active-y" style="height: 348px;" data-ps-id="74467d3a-1933-54d9-a104-a81940ede8d3">
                    <li class="sidebar-header">-- Main</li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Home" asp-action="Index">
                            Dashboard 1
                        </a>
                    </li>
                    <li class="sidebar-item  ">
                        <a class="sidebar-link" asp-controller="Lawsuits" asp-action="Index">Lawsuits </a>
                    </li>
                    <li class="sidebar-item  ">
                        <a class="sidebar-link" asp-controller="Courts" asp-action="Index">Courts </a>
                    </li>
                    <li class="sidebar-item  ">
                        <a class="sidebar-link" asp-controller="SMS" asp-action="Index">SMS </a>
                    </li>



                </ul>
            </div>
        </nav>
        <!-- ======= Sidebar ======= -->


        <div class="main">
            <nav class="navbar navbar-expand navbar-light bg-white">
                <a class="sidebar-toggle d-flex mr-2">
                    <i class="hamburger align-self-center"></i>
                </a>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <form class="form-inline d-none d-sm-inline-block">
                                <input class="form-control form-control-no-border mr-sm-2 searchinputbox" type="text" placeholder="Search projects..." aria-label="Search">
                            </form>
                        </li>
                        
                        <li class="nav-item dropdown">
                            @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-toggle="dropdown">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings align-middle"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
                            </a>


                            <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-toggle="dropdown">
                                <img src="~/img/profile-img.jpg" class="avatar img-fluid rounded-circle mr-1" alt="Garrett Winters">
                                <span class="text-dark">


                                    @User.Identity.Name
                                    


                                </span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item"  asp-controller="account" asp-action="Profile" asp-route-email=@User.Identity.Name>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user feathersmall"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                    Profile
                                </a>



                                <a class="dropdown-item" asp-action="Logout" asp-controller="Account">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out feathersmall"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>Sign out
                                </a>
                            </div>
                            }
                        </li>
                        
                    </ul>
                </div>
            </nav>
            <main class="content">
                <div class="container-fluid p-0">
                    <partial name="_Notifications" />
                    @RenderBody()
                </div>

            </main>
            <div class="modal" tabindex="-1" role="dialog" id="form-modal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title"></h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">

                        </div>
                    </div>
                </div>
            </div>

            <div class="loaderbody" id="loaderbody">
                <div class="loader"></div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/feather.min.js"></script>
    <script src="~/js/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/prism.js"></script>
    <script src="~/js/datatables.js"></script>
 

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Diary.UI/Views/Shared/_Modal.cshtml
<div class="modal fade" id="AddHearing">
  
</div>

Diary.UI/Views/Shared/_Model.cshtml
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Student Details Form</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="studentFormDetails">

            </div>
            <div class="modal-footer">
                <input id="btnSubmit" type="submit" value="Submit" class="btn btn-primary" />
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>